config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations"
  }
  root 'pages#home' 

  resources :albums
  resources :checkpoints
  resources :photos
  resources :posts
  resources :subscribers
  resources :trips

  get '/avatar' => 'user#new_avatar'

  get '/stats' => 'admin#stats', as: :stats

  get '/about' => 'pages#about', as: :about
  get '/contact' => 'pages#contact', as: :contact
  get '/index' => 'pages#home', as: :home
  get '/test' => 'pages#test'
  get '/wedding' => 'pages#wedding'

  post 'posts/email_post' => 'posts#email_post'

end

app/models/album.rb
class Album < ActiveRecord::Base
  include ImpressionableExtension
  has_many :photos, :inverse_of => :album
  accepts_nested_attributes_for :photos, allow_destroy: true
  validates_presence_of :title
  
  before_create :set_slug
  before_destroy :destroy_photos
  is_impressionable

  scope :top5,
    select("id, count(impression.id) AS impressions_count").joins(:impression).group("id").order("impressions_count DESC")


  def set_slug
    self.slug = self.title.parameterize 
  end

  def to_param
    slug
  end

  def cover_photo_url
    photos.first.image.large rescue "bay-bridge.jpg"
  end

  def destroy_photos
    photos.destroy_all
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :new, :destroy]
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  def index
    @albums = Album.all.order('created_at DESC').page(params[:page]).per_page(10)
    @top_posts = Post.top(5)
    @top_albums = Album.top(5)
  end

  # GET /albums/1
  def show
    log_impression
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      # to handle multiple images upload on create
      if params[:images]
        params[:images].each { |image|
          @album.photos.create(image: image)
        }
      end
      flash[:notice] = "Your album has been created."
      redirect_to @album
    else 
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  def update
    if @album.update(album_params)
      # to handle multiple images upload on update when user add more picture
      if params[:images]
        params[:images].each { |image|
          @album.photos.create(image: image)
        }
      end
      flash[:notice] = "Album has been updated."
      redirect_to @album
    else
      render :edit
    end
  end

  # DELETE /albums/1
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def log_impression
    impressionist(@album) 
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_album
    @album = Album.find_by_slug(params[:id]) || Album.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def album_params
    params.require(:album).permit(:id, :title, :slug, :description, :created_at, :updated_at, photos_attributes: [ :description, :album_id, :image, :id, :created_at, :updated_at, :_destroy ])
  end
end

app/views/albums/_form.html.slim
= form_for @album, :html => {:multipart => true} do |f|
  .row
    .col-sm-6.col-sm-offset-3
      .form-group
        = f.label :title, class: 'control-label'
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :description, class: 'control-label'
        = f.text_field :description, class: 'form-control'
      .form-group
        = label_tag "Choose Images"
        = file_field_tag "images[]", type: :file, multiple: true
      .form-group
        = link_to 'Cancel', @album, class: "btn btn-default"
        = f.submit "Save", :class => "btn btn-success"
  .form-group
    = f.fields_for :photos do |p|
      .col-sm-3
        img class="photo" src=p.object.image.small

        label.control-label
          | Description
          = p.text_area :description, class: 'form-control', placeholder: p.object.description

        label.checkbox.text-center
          = p.check_box :_destroy
          |  Remove photo 

app/views/albums/edit.html.slim
h1 Edit Album
= render 'form'

app/views/albums/index.html.slim
- content_for :title do
  | Photo Albums
- content_for :description do
  | What have Liz and Nathan been doing with their time? Check out the photos and see!

.row
  .col-sm-2.hidden-xs style="position: fixed;"
    = render partial: "layouts/top_content_sidebar", :locals => {:top_posts => @top_posts, :top_albums => @top_albums}

  .col-sm-9.col-sm-offset-3
      - for album in @albums
        .row 
          .col-xs-12.col-pad-all
            a href=album_url(album)
              div.image-zoom
                h2.centered-axis-xy.text-center = album.title
                img src=image_url(album.cover_photo_url)

.row.center-block.text-center
  = will_paginate @albums, renderer: BootstrapPagination::Rails

- if user_signed_in?
  a href=new_album_path New Album

app/views/albums/new.html.slim
h1 New album
= render 'form'

app/views/albums/show.html.slim
- content_for :title do
  = @album.title
- content_for :description do
  = truncate((strip_tags @album.description), length: 100)
#albums.row
  .col-sm-12.header.text-center
    h1
      = @album.title
    p.body
      = simple_format @album.description
    p.date
      = @album.created_at.strftime("%d %B %Y")
  = render_gallery_for @album.photos.order('created_at'), list_tag: :div, list_class: 'col-sm-12', item_tag: :p, item_class: 'col-sm-3', title: 'description' 
  - if user_signed_in?
    .col-sm-12.text-center
      = link_to 'Edit Album', edit_album_path(@album) , class: "btn btn-success"