config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations"
  }
  root 'pages#home' 

  resources :albums
  resources :checkpoints
  resources :photos
  resources :posts
  resources :subscribers
  resources :trips

  get '/avatar' => 'user#new_avatar'

  get '/stats' => 'admin#stats', as: :stats

  get '/about' => 'pages#about', as: :about
  get '/contact' => 'pages#contact', as: :contact
  get '/index' => 'pages#home', as: :home
  get '/test' => 'pages#test'
  get '/wedding' => 'pages#wedding'

  post 'posts/email_post' => 'posts#email_post'

end

app/models/photo.rb
class Photo < ActiveRecord::Base 
  belongs_to :album
  mount_uploader :image, ImageUploader
  store_in_background :image

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :new, :destroy]
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.all.order('created_at DESC').page(params[:page]).per_page(10)
  end

  def show
  end


  def new
    @photo = Photo.new
  end


  def edit
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.save
  end

  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:album_id, :image, :id, :created_at, :updated_at, :description)
    end
end

app/views/photos/create.js.erb
<% if @photo.persisted? %>
  $('#upload_<%=params[:unique_id]%>').hide();
<% else %>
  $('#upload_<%=params[:unique_id]%> div.progress').removeClass('active progress-striped').addClass('progress-danger');
<% end %>

app/views/photos/index.html.erb
<div class="row">
  <% @photos.each do |photo| %>
    <%= image_tag photo.upload(:original) %>
  <% end %>
</div>

<div class="row center-block text-center">
  <%= will_paginate @photos, renderer: BootstrapPagination::Rails %>
</div>

<% if user_signed_in? %>
  <%= link_to 'New photo', new_photo_path %>
<% end %>

app/views/photos/new.html.erb
<h1>Upload photos</h1>


<% albums_array = Album.all.map{ |album| [album.title, album.id] } %>
<%= select_tag(:album_id, options_for_select(albums_array), class: "form-control") %>

<%= s3_uploader_form callback_url: photos_url,
  id: "s3_uploader",
  callback_param: "photo[direct_upload_url]",
  expiration: 24.hours.from_now.utc.iso8601,
  max_file_size: 100.megabytes do %>
  <%= file_field_tag :file, multiple: true %>
<% end %>



<div id="uploads_container"></div>

<script id="template-upload" type="text/x-tmpl">
<div id="upload_{%=o.unique_id%}" class="upload">
  <h5>{%=o.name%}</h5>
  <div class="progress progress-striped active"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

<%= link_to 'Back', photos_path %>
<%= link_to 'Create a new album', new_album_path %>

<!-- -->

app/views/photos/show.html.erb
Show!