config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations"
  }
  root 'pages#home' 

  resources :albums
  resources :checkpoints
  resources :photos
  resources :posts
  resources :subscribers
  resources :trips

  get '/avatar' => 'user#new_avatar'

  get '/stats' => 'admin#stats', as: :stats

  get '/about' => 'pages#about', as: :about
  get '/contact' => 'pages#contact', as: :contact
  get '/index' => 'pages#home', as: :home
  get '/test' => 'pages#test'
  get '/wedding' => 'pages#wedding'

  post 'posts/email_post' => 'posts#email_post'

end

app/views/layouts/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= alert %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container footer-container">
    <div class="row footer-content">
      <span class="pull-left">&#xa9; 2014 Liz Hubertz</span>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top" role="navigation">
    <div class="navbar-inner">
      <div class="container">

        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <div class="nav-collapse">
          <ul class="nav text-uppercase text-headings">
            <% if user_signed_in? %>
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            <% end %>
              <li><%= link_to "About", about_path, :class => 'navbar-link'  %></li>
              <li><%= link_to "Blog", posts_path, :class => 'navbar-link'  %></li>
              <li><%= link_to image_tag('logo-gray.png', class: "navbar-logo"), root_path, :class => 'navbar-link hidden-xs' %></li>
              <li><%= link_to "Photos", about_path, :class => 'navbar-link'  %></li>
              <li><%= link_to "Map", about_path, :class => 'navbar-link'  %></li>
          </ul>
        </div>

      </div><!-- /.container-->
    </div><!-- navbar-inner -->
  </nav>
</header>

app/views/layouts/_top_content_sidebar.html.slim
/ - unless @top_posts.empty?
/ h5
/  | Most 
/  i.fa.fa-heart-o
/  |  Posts
/ table.table
/   - for post in @top_posts
/     tr
/       td.title = link_to(post.title, post)

- unless @top_albums.empty?
h5
 | Most 
 i.fa.fa-heart-o
 |  Albums
table.table
  - for album in @top_albums
    tr
      td.title = link_to(album.title, album)

app/views/layouts/_wedding_header.html.erb
<head>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>

<style type="text/css">

#navbar-usermanagement{font-family:sans-serif;border-width:0 !important;border-radius:0 !important;margin:0 !important;/*padding-right:116px;*/text-transform: uppercase;}
#navbar-usermanagement.navbar{min-height:32px;}
#navbar-usermanagement .navbar-nav>li>a{color:#b0abb6 !important;padding:7px 15px;}
.purple{background-color:#3e3c54 !important;}

#navbar-main{background-color: white; border-radius:0 !important;border-color:#b0abb6;border-width:0 0 2px 0;border-style:solid;/*padding-right:58px;*/}
#navbar-main .cta{background-color:#d2373b;border-radius:20px;color:#fff;}
#navbar-main.navbar{margin-bottom:0 !important;}
#navbar-main .navbar-nav>li>a{/*line-height:51px;*/font-family:sans-serif;padding-top:5px !important;padding-bottom:5px !important;}
#navbar-main .navbar-brand{height:81px;padding:0 !important;line-height:81px !important;}
#navbar-main #navbar ul{margin-top:25px;}
.navbar-default .navbar-toggle, .navbar-default .navbar-toggle:focus, .navbar-default .navbar-toggle:hover { border: none; background-color: transparent !important; }

.navbar-brand{margin-left:0 !important;}

/* Large devices (large desktops, 1200px and up) */
@media (min-width: 1200px) {
  .container { width: 980px; }
}

/* Smaller than desktops, start at tablet size */
@media (max-width: 768px) {
    #navbar-main .navbar-brand{ height: 50px; }
    #navbar-main .navbar-brand img{ max-height: 50px; }
    #navbar-main .navbar-nav>li:not(:last-child)>a { border-bottom: 1px solid #afaab5; }
}

/* Always place content below navbar */
main {
  margin-top: 150px;
}
/* Override bootstrap blue */
main a {
	color: #3a3d51;
}

/* Footer */

#guarantee { line-height: 1.15em; margin-top: 30px; font-size: 28px; font-weight: lighter; }
#guarantee .text-xl { font-size: 40px; font-weight: bold; }

@media (max-width: 768px) {
  #guarantee { text-align: center; }
  #copyrightTerms { text-align: center; margin: 0; }
}

/* Big devices - get rid of padding-top so transparent navbar shines through */
body.home { padding-top: 115px; }
@media (min-width: 1200px) {
  body.home {padding-top: 0;}

  /* Insert that padding back in the homepage hero section */
  .home #homepage-hero-heading, .home .carousel-control { margin-top: 115px; /* specifically for 'broken' carousel */position: absolute; top: 0; right: 20px; }
}
@media (max-width: 768px) {
  body.home {padding-top: 105px; }
}

.homepage-hero-image{height:auto; max-height: 440px; padding: 0px;}

#homepage-heroes { background-image: url("http://previews.123rf.com/images/epokrovsky/epokrovsky1107/epokrovsky110700015/9896533-Tourist-taking-a-picture-of-the-Eiffel-Tower-in-Paris-Stock-Photo.jpg");
background-size: cover; height: 500px; }

@media (max-width: 768px) {
  #homepage-heroes { height: 300px; }
}

</style>


<div id="navs" class="navbar-fixed-top">
    <nav id="navbar-usermanagement" class="purple navbar navbar-default" style="background-color: #3e3c54;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="navbar-header">
                        <img src="//p4.zdassets.com/hc/theme_assets/209329/200128955/logo-panasonic-small.png" alt="" border="0" />
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="#login" data-toggle="modal" data-target="#modal-login">login</a></li>
                            <li><a href="/store/cart"><img src="//p4.zdassets.com/hc/theme_assets/209329/200128955/icon-lock.png" alt="" border="0" /></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <nav id="navbar-main" class="navbar navbar-default">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"><img class="img-responsive" src="//p4.zdassets.com/hc/theme_assets/209329/200128955/nubo-logo-nomarginleft.png" alt="Nubo" border="0" /></a>
                    </div>
                </div>
                <div class="col-md-10">
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">

                          <li><a href="http://liznubo.bigandbrown.com/home">Home</a></li>
                          <li><a href="http://liznubo.bigandbrown.com/products">Products</a></li>
                          <li><a href="http://liznubo.bigandbrown.com/store">Store</a></li>
                          <li><a class="cta" href="http://liznubo.bigandbrown.com/store">Pre-Order</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta charset="UTF-8"
    
    script src="https://use.typekit.net/afe4bbx.js"
    javascript: 
      try{Typekit.load({ async: true });}catch(e){}

    ruby:
      title = content_for?(:title) ? content_for(:title) : "Liz Hubertz Blog and Experimentation Zone"
    title
      | Ginger and the Cyclist - #{title}

    ruby:
      description = content_for?(:description) ? content_for(:description) : 'Follow Liz and Nathan as they travel the world as digital nomads'
    meta name="description=" content="#{description}"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    script[src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false" type="text/javascript"]
    script[src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"]

    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-60258450-1', 'auto'); ga('send', 'pageview'); 

  body id=controller_name
    .flash
      = render partial: "layouts/flash"
    = render partial: "layouts/header"

    main
      .container
        = yield
     
  = render partial: "layouts/footer"